import { Match, Product } from './notion';

// Productos de ejemplo con las 4 imágenes específicas de Camach
export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Sudadera Suva',
    description: 'Sudadera deportiva de alta calidad',
    price: 549.00,
    imageUrl: 'https://camach.com.mx/cdn/shop/products/2_e5c0fe77-2ab6-4a9d-9b94-71cb50770317_684x@2x.jpg?v=1638983896',
    link: 'https://camach.com.mx/collections/nuevos/products/sudadera-suva-3',
  },
  {
    id: '2',
    name: 'Sudadera Suva',
    description: 'Sudadera deportiva de alta calidad',
    price: 549.00,
    imageUrl: 'https://camach.com.mx/cdn/shop/products/2_2e1161d8-3dd7-4c3c-b826-3d871ca900e9_684x@2x.jpg?v=1638983744',
    link: 'https://camach.com.mx/collections/nuevos/products/sudadera-suva-2',
  },
  {
    id: '3',
    name: 'Sudadera Suva',
    description: 'Sudadera deportiva de alta calidad',
    price: 549.00,
    imageUrl: 'https://camach.com.mx/cdn/shop/products/2_d5c2a1cf-0801-4c6a-9973-6a3a0f2bc069_684x@2x.jpg?v=1638983238',
    link: 'https://camach.com.mx/collections/nuevos/products/sudadera-suva-1',
  },
  {
    id: '4',
    name: 'Sudadera Winter',
    description: 'Sudadera para temporada invernal',
    price: 750.00,
    imageUrl: 'https://camach.com.mx/cdn/shop/products/2_0dfdf855-c361-4d9a-82c2-e924e930d119_684x@2x.jpg?v=1636744906',
    link: 'https://camach.com.mx/collections/nuevos/products/sudadera-winter-1',
  },
];

// Partidos del 9 de noviembre - Dual Meet Asturiano vs Hacienda
// Todos los partidos pertenecen al torneo con id '1'
export const mockMatches: Match[] = [
  // Nov 9 - 09:30
  {
    id: '1',
    date: '9 nov',
    rawDate: '2025-11-09',
    time: '09:30',
    status: 'pendiente',
    player1: { name: 'Karen Muñiz', club: 'Asturiano' },
    player2: { name: 'Fernanda López', club: 'Hacienda' },
    tournamentId: '1', // Pertenece al torneo "Dual Meet Asturiano Vs Hacienda"
  },
  {
    id: '2',
    date: '9 nov',
    rawDate: '2025-11-09',
    time: '09:30',
    status: 'pendiente',
    player1: { name: 'Gabriela Rodríguez', club: 'Asturiano' },
    player2: { name: 'Sofía Cisneros', club: 'Hacienda' },
    tournamentId: '1',
  },
  // 09:50
  {
    id: '3',
    date: '9 nov',
    rawDate: '2025-11-09',
    time: '09:50',
    status: 'pendiente',
    player1: { name: 'Santiago Casarrubias', club: 'Asturiano' },
    player2: { name: 'David Camacho', club: 'Hacienda' },
    tournamentId: '1',
  },
  {
    id: '4',
    date: '9 nov',
    rawDate: '2025-11-09',
    time: '09:50',
    status: 'pendiente',
    player1: { name: 'Mario Toledano', club: 'Asturiano' },
    player2: { name: 'Adriana Martínez', club: 'Hacienda' },
    tournamentId: '1',
  },
  // 10:10
  {
    id: '5',
    date: '9 nov',
    rawDate: '2025-11-09',
    time: '10:10',
    status: 'pendiente',
    player1: { name: 'Raúl Álvarez', club: 'Asturiano' },
    player2: { name: 'Héctor Cisneros', club: 'Hacienda' },
    tournamentId: '1',
  },
  {
    id: '6',
    date: '9 nov',
    rawDate: '2025-11-09',
    time: '10:10',
    status: 'pendiente',
    player1: { name: 'Abraham Figueroa', club: 'Asturiano' },
    player2: { name: 'Ramón Palafox', club: 'Hacienda' },
    tournamentId: '1',
  },
  // 10:30
  {
    id: '7',
    date: '9 nov',
    rawDate: '2025-11-09',
    time: '10:30',
    status: 'pendiente',
    player1: { name: 'Jesús Luna', club: 'Asturiano' },
    player2: { name: 'Ismael Monroy', club: 'Hacienda' },
    tournamentId: '1',
  },
  {
    id: '8',
    date: '9 nov',
    rawDate: '2025-11-09',
    time: '10:30',
    status: 'pendiente',
    player1: { name: 'Cristian Torres', club: 'Asturiano' },
    player2: { name: 'Gabriel Zarco', club: 'Hacienda' },
    tournamentId: '1',
  },
  // 10:40
  {
    id: '9',
    date: '9 nov',
    rawDate: '2025-11-09',
    time: '10:40',
    status: 'pendiente',
    player1: { name: 'Francsco Trejo', club: 'Asturiano' },
    player2: { name: 'Jacqueline Camacho', club: 'Hacienda' },
    tournamentId: '1',
  },
  {
    id: '10',
    date: '9 nov',
    rawDate: '2025-11-09',
    time: '10:40',
    status: 'pendiente',
    player1: { name: 'Job Ascárraga', club: 'Asturiano' },
    player2: { name: 'Mauricio Brauer', club: 'Hacienda' },
    tournamentId: '1',
  },
  // 11:00
  {
    id: '11',
    date: '9 nov',
    rawDate: '2025-11-09',
    time: '11:00',
    status: 'pendiente',
    player1: { name: 'Ghiberti Alonso', club: 'Asturiano' },
    player2: { name: 'Kevin Pedroza', club: 'Hacienda' },
    tournamentId: '1',
  },
  {
    id: '12',
    date: '9 nov',
    rawDate: '2025-11-09',
    time: '11:00',
    status: 'pendiente',
    player1: { name: 'Manuel González', club: 'Asturiano' },
    player2: { name: 'Julio Téllez', club: 'Hacienda' },
    tournamentId: '1',
  },
  // 11:20
  {
    id: '13',
    date: '9 nov',
    rawDate: '2025-11-09',
    time: '11:20',
    status: 'pendiente',
    player1: { name: 'Karen Muñiz', club: 'Asturiano' },
    player2: { name: 'Sofía Cisneros', club: 'Hacienda' },
    tournamentId: '1',
  },
  {
    id: '14',
    date: '9 nov',
    rawDate: '2025-11-09',
    time: '11:20',
    status: 'pendiente',
    player1: { name: 'Gabriela Rodríguez', club: 'Asturiano' },
    player2: { name: 'Fernanda López', club: 'Hacienda' },
    tournamentId: '1',
  },
  // 11:40
  {
    id: '15',
    date: '9 nov',
    rawDate: '2025-11-09',
    time: '11:40',
    status: 'pendiente',
    player1: { name: 'Santiago Casarrubias', club: 'Asturiano' },
    player2: { name: 'Adriana Martínez', club: 'Hacienda' },
    tournamentId: '1',
  },
  {
    id: '16',
    date: '9 nov',
    rawDate: '2025-11-09',
    time: '11:40',
    status: 'pendiente',
    player1: { name: 'Mario Toledano', club: 'Asturiano' },
    player2: { name: 'David Camacho', club: 'Hacienda' },
    tournamentId: '1',
  },
  // 12:00
  {
    id: '17',
    date: '9 nov',
    rawDate: '2025-11-09',
    time: '12:00',
    status: 'pendiente',
    player1: { name: 'Raúl Álvarez', club: 'Asturiano' },
    player2: { name: 'Ramón Palafox', club: 'Hacienda' },
    tournamentId: '1',
  },
  {
    id: '18',
    date: '9 nov',
    rawDate: '2025-11-09',
    time: '12:00',
    status: 'pendiente',
    player1: { name: 'Abraham Figueroa', club: 'Asturiano' },
    player2: { name: 'Héctor Cisneros', club: 'Hacienda' },
    tournamentId: '1',
  },
  // 12:20
  {
    id: '19',
    date: '9 nov',
    rawDate: '2025-11-09',
    time: '12:20',
    status: 'pendiente',
    player1: { name: 'Jesús Luna', club: 'Asturiano' },
    player2: { name: 'Gabriel Zarco', club: 'Hacienda' },
    tournamentId: '1',
  },
  {
    id: '20',
    date: '9 nov',
    rawDate: '2025-11-09',
    time: '12:20',
    status: 'pendiente',
    player1: { name: 'Cristian Torres', club: 'Asturiano' },
    player2: { name: 'Ismael Monroy', club: 'Hacienda' },
    tournamentId: '1',
  },
  // 12:40
  {
    id: '21',
    date: '9 nov',
    rawDate: '2025-11-09',
    time: '12:40',
    status: 'pendiente',
    player1: { name: 'Francsco Trejo', club: 'Asturiano' },
    player2: { name: 'Mauricio Brauer', club: 'Hacienda' },
    tournamentId: '1',
  },
  {
    id: '22',
    date: '9 nov',
    rawDate: '2025-11-09',
    time: '12:40',
    status: 'pendiente',
    player1: { name: 'Job Ascárraga', club: 'Asturiano' },
    player2: { name: 'Jacqueline Camacho', club: 'Hacienda' },
    tournamentId: '1',
  },
  // 13:00
  {
    id: '23',
    date: '9 nov',
    rawDate: '2025-11-09',
    time: '13:00',
    status: 'pendiente',
    player1: { name: 'Ghiberti Alonso', club: 'Asturiano' },
    player2: { name: 'Julio Téllez', club: 'Hacienda' },
    tournamentId: '1',
  },
  {
    id: '24',
    date: '9 nov',
    rawDate: '2025-11-09',
    time: '13:00',
    status: 'pendiente',
    player1: { name: 'Manuel González', club: 'Asturiano' },
    player2: { name: 'Kevin Pedroza', club: 'Hacienda' },
    tournamentId: '1',
  },
];
